version: '3.8'
services:
  db:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=autospace
    volumes:
      - autospace_pg_data:/bitnami/postgresql

volumes:
  autospace_pg_data: